[2025-01-04T14:13:23.320+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-04T14:13:18.145789+00:00 [queued]>
[2025-01-04T14:13:23.337+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-04T14:13:18.145789+00:00 [queued]>
[2025-01-04T14:13:23.338+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-04T14:13:23.357+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-04 14:13:18.145789+00:00
[2025-01-04T14:13:23.369+0000] {standard_task_runner.py:60} INFO - Started process 152 to run task
[2025-01-04T14:13:23.374+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'manual__2025-01-04T14:13:18.145789+00:00', '--job-id', '1818', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpsjqtxiie']
[2025-01-04T14:13:23.378+0000] {standard_task_runner.py:88} INFO - Job 1818: Subtask ft_balance_f
[2025-01-04T14:13:23.457+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f manual__2025-01-04T14:13:18.145789+00:00 [running]> on host 11306dadb3f6
[2025-01-04T14:13:23.590+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abershits' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T14:13:18.145789+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-04T14:13:18.145789+00:00'
[2025-01-04T14:13:28.692+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T14:13:28.868+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T14:13:28.895+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-04T14:13:28.930+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20250104T141318, start_date=20250104T141323, end_date=20250104T141328
[2025-01-04T14:13:29.011+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-04T14:13:29.090+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
