[2025-01-04T16:55:34.360+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-04T16:55:31.678318+00:00 [queued]>
[2025-01-04T16:55:34.384+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-04T16:55:31.678318+00:00 [queued]>
[2025-01-04T16:55:34.385+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-04T16:55:34.419+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-04 16:55:31.678318+00:00
[2025-01-04T16:55:34.441+0000] {standard_task_runner.py:60} INFO - Started process 163 to run task
[2025-01-04T16:55:34.449+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'manual__2025-01-04T16:55:31.678318+00:00', '--job-id', '1894', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpvi69abpd']
[2025-01-04T16:55:34.455+0000] {standard_task_runner.py:88} INFO - Job 1894: Subtask ft_balance_f
[2025-01-04T16:55:34.966+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f manual__2025-01-04T16:55:31.678318+00:00 [running]> on host 545032134f28
[2025-01-04T16:55:35.088+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abershits' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T16:55:31.678318+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-04T16:55:31.678318+00:00'
[2025-01-04T16:55:48.998+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T16:56:37.180+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T16:56:37.770+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-04T16:56:38.007+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20250104T165531, start_date=20250104T165534, end_date=20250104T165638
[2025-01-04T16:56:38.399+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-04T16:56:38.584+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
