[2025-01-04T17:28:26.927+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-04T17:28:24.661234+00:00 [queued]>
[2025-01-04T17:28:26.952+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-04T17:28:24.661234+00:00 [queued]>
[2025-01-04T17:28:26.953+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-04T17:28:26.981+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-04 17:28:24.661234+00:00
[2025-01-04T17:28:26.994+0000] {standard_task_runner.py:60} INFO - Started process 327 to run task
[2025-01-04T17:28:27.002+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'manual__2025-01-04T17:28:24.661234+00:00', '--job-id', '1908', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpx_0v0zu7']
[2025-01-04T17:28:27.007+0000] {standard_task_runner.py:88} INFO - Job 1908: Subtask ft_balance_f
[2025-01-04T17:28:27.552+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f manual__2025-01-04T17:28:24.661234+00:00 [running]> on host ef69f4633403
[2025-01-04T17:28:27.684+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abershits' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T17:28:24.661234+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-04T17:28:24.661234+00:00'
[2025-01-04T17:28:33.298+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T17:31:17.749+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T17:31:17.863+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-04T17:31:18.072+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20250104T172824, start_date=20250104T172826, end_date=20250104T173118
[2025-01-04T17:31:18.363+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-04T17:31:18.603+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
